/* eslint-disable */
/* tslint:disable */
/* auto-generated by NAPI-RS */

/**
 * @hexcore/helix — Native binary loader
 *
 * Automatically loads the correct platform-specific native binary.
 * Supported platforms: win32-x64, linux-x64, darwin-arm64, darwin-x64.
 */

const { existsSync, readFileSync } = require('fs');
const { join } = require('path');

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
    // For Node.js >= 15: report.getReport().header.glibcVersionRuntime
    if (!process.report || typeof process.report.getReport !== 'function') {
        try {
            const lddPath = require('child_process')
                .execSync('which ldd')
                .toString()
                .trim();
            return readFileSync(lddPath, 'utf8').includes('musl');
        } catch {
            return true;
        }
    } else {
        const report = process.report.getReport();
        const rpt = typeof report === 'string' ? JSON.parse(report) : report;
        return !rpt.header.glibcVersionRuntime;
    }
}

switch (platform) {
    case 'win32':
        switch (arch) {
            case 'x64':
                localFileExisted = existsSync(
                    join(__dirname, 'hexcore-helix.win32-x64-msvc.node')
                );
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./hexcore-helix.win32-x64-msvc.node');
                    } else {
                        nativeBinding = require('@hexcore/helix-win32-x64-msvc');
                    }
                } catch (e) {
                    loadError = e;
                }
                break;
            default:
                throw new Error(`Unsupported architecture on Windows: ${arch}`);
        }
        break;

    case 'linux':
        switch (arch) {
            case 'x64':
                if (isMusl()) {
                    localFileExisted = existsSync(
                        join(__dirname, 'hexcore-helix.linux-x64-musl.node')
                    );
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./hexcore-helix.linux-x64-musl.node');
                        } else {
                            nativeBinding = require('@hexcore/helix-linux-x64-musl');
                        }
                    } catch (e) {
                        loadError = e;
                    }
                } else {
                    localFileExisted = existsSync(
                        join(__dirname, 'hexcore-helix.linux-x64-gnu.node')
                    );
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./hexcore-helix.linux-x64-gnu.node');
                        } else {
                            nativeBinding = require('@hexcore/helix-linux-x64-gnu');
                        }
                    } catch (e) {
                        loadError = e;
                    }
                }
                break;
            default:
                throw new Error(`Unsupported architecture on Linux: ${arch}`);
        }
        break;

    case 'darwin':
        switch (arch) {
            case 'x64':
                localFileExisted = existsSync(
                    join(__dirname, 'hexcore-helix.darwin-x64.node')
                );
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./hexcore-helix.darwin-x64.node');
                    } else {
                        nativeBinding = require('@hexcore/helix-darwin-x64');
                    }
                } catch (e) {
                    loadError = e;
                }
                break;
            case 'arm64':
                localFileExisted = existsSync(
                    join(__dirname, 'hexcore-helix.darwin-arm64.node')
                );
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./hexcore-helix.darwin-arm64.node');
                    } else {
                        nativeBinding = require('@hexcore/helix-darwin-arm64');
                    }
                } catch (e) {
                    loadError = e;
                }
                break;
            default:
                throw new Error(`Unsupported architecture on macOS: ${arch}`);
        }
        break;

    default:
        throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
    if (loadError) {
        throw loadError;
    }
    throw new Error(
        `Failed to load native binding for @hexcore/helix on ${platform}-${arch}`
    );
}

const {
    HelixEngine,
    Architecture,
    serializeCfg,
    serializeAst,
    readCfgFunctionName,
} = nativeBinding;

module.exports.HelixEngine = HelixEngine;
module.exports.Architecture = Architecture;
module.exports.serializeCfg = serializeCfg;
module.exports.serializeAst = serializeAst;
module.exports.readCfgFunctionName = readCfgFunctionName;
