/* eslint-disable */
/* tslint:disable */
/* auto-generated by NAPI-RS */

/**
 * @hexcore/helix — TypeScript Type Declarations
 *
 * Provides full type safety for the Helix decompilation engine
 * when used from TypeScript/VS Code extensions.
 */

/** Target CPU architecture for the decompiler. */
export const enum Architecture {
    X86 = 0,
    X86_64 = 1,
    Arm = 2,
    Aarch64 = 3,
    Mips = 4,
    Mips64 = 5,
    PowerPc = 6,
    PowerPc64 = 7,
    Sparc = 8,
    Sparc64 = 9,
    Riscv32 = 10,
    Riscv64 = 11,
}

/** Result of a decompilation operation. */
export interface DecompileResult {
    /** Decompiled pseudo-C source code. */
    source: string;
    /** Function name. */
    functionName: string;
    /** Entry address as hex string. */
    entryAddress: string;
    /** Number of basic blocks in the CFG. */
    blockCount: number;
    /** Number of instructions analyzed. */
    instructionCount: number;
    /** Raw FlatBuffer data for the CFG (for Graph View zero-copy rendering). */
    cfgBuffer: Buffer | null;
    /** Raw FlatBuffer data for the AST (for AST View zero-copy rendering). */
    astBuffer: Buffer | null;
}

/** The Helix decompilation engine. */
export class HelixEngine {
    /**
     * Create a new Helix engine instance.
     * @param arch - Target architecture for decompilation.
     */
    constructor(arch: Architecture);

    /** Get the engine version string. */
    version(): string;

    /** Get the target architecture name. */
    architecture(): string;

    /**
     * Decompile a binary buffer starting at the given entry address.
     *
     * @param data - Raw binary data.
     * @param baseAddress - Base virtual address where the data is loaded.
     * @param entryAddress - Entry point address to start decompilation.
     * @returns Decompilation result with source code and optional FlatBuffer data.
     *
     * @example
     * ```typescript
     * import { HelixEngine, Architecture } from '@hexcore/helix';
     *
     * const engine = new HelixEngine(Architecture.X86_64);
     * const binary = fs.readFileSync('target.exe');
     * const result = engine.decompile(binary, 0x400000n, 0x401000n);
     * console.log(result.source);
     * engine.dispose();
     * ```
     */
    decompile(data: Buffer, baseAddress: bigint, entryAddress: bigint): DecompileResult;

    /**
     * Decompile Remill LLVM IR text into pseudo-C source code.
     *
     * This is the **primary integration path** for the HexCore IDE.
     * Takes the raw IR text output from `hexcore-remill` and transforms
     * it into human-readable decompiled code.
     *
     * @param irText - The LLVM IR text from `hexcore-remill`.
     * @returns Decompilation result with pseudo-C source code.
     *
     * @example
     * ```typescript
     * const engine = new HelixEngine(Architecture.X86_64);
     * const irText = fs.readFileSync('lifted.ll', 'utf-8');
     * const result = engine.decompileIr(irText);
     * console.log(result.source);
     * engine.dispose();
     * ```
     */
    decompileIr(irText: string): DecompileResult;

    /**
     * Decompile Remill LLVM IR and return pipeline performance metrics.
     *
     * Same as `decompileIr` but also returns timing, throughput, and
     * diagnostic data for performance monitoring.
     *
     * @param irText - The LLVM IR text from `hexcore-remill`.
     * @returns Tuple of [result, metrics].
     */
    decompileIrWithMetrics(irText: string): [DecompileResult, PipelineMetricsResult];

    /** Release engine resources. The engine cannot be used after this call. */
    dispose(): void;

    /** Check if the engine has been disposed. */
    get isDisposed(): boolean;
}

/** Pipeline performance metrics. */
export interface PipelineMetricsResult {
    /** Total pipeline duration in milliseconds. */
    totalMs: number;
    /** Number of instructions decoded. */
    instructionsDecoded: number;
    /** Number of functions recovered. */
    functionsRecovered: number;
    /** Throughput in instructions per millisecond. */
    throughput: number;
    /** Number of warnings generated. */
    warningCount: number;
}

/**
 * Serialize a CFG JSON string into a FlatBuffer for the Graph View.
 * @param cfgJson - JSON representation of the control flow graph.
 * @returns FlatBuffer binary data.
 */
export function serializeCfg(cfgJson: string): Buffer;

/**
 * Serialize an AST JSON string into a FlatBuffer for the AST View.
 * @param astJson - JSON representation of the abstract syntax tree.
 * @returns FlatBuffer binary data.
 */
export function serializeAst(astJson: string): Buffer;

/**
 * Read the function name from a CFG FlatBuffer without full deserialization.
 * Demonstrates zero-copy access.
 * @param buffer - FlatBuffer containing CFG data.
 * @returns Function name, or null if the buffer is empty/invalid.
 */
export function readCfgFunctionName(buffer: Buffer): string | null;
