/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The Helix decompilation engine.
 *
 * Usage from TypeScript:
 * ```typescript
 * import { HelixEngine, Architecture } from '@hexcore/helix';
 *
 * const engine = new HelixEngine(Architecture.X86_64);
 * const result = engine.decompileIr(irText);
 * console.log(result.source);  // pseudo-C from MLIR pipeline
 * engine.dispose();
 * ```
 */
export declare class HelixEngine {
  /** Create a new Helix engine instance for the specified architecture. */
  constructor(arch: Architecture)
  /**
   * Set whether to skip optimization passes in the MLIR pipeline.
   * When true, Tier 2.5 passes (magic division, devirtualization) are skipped.
   * Must be called before the first decompile call.
   */
  setSkipOptimization(skip: boolean): void
  /**
   * Enable the C AST layer for emission (--use-cast-layer).
   * When enabled, uses CAstBuilder → CAstOptimizer → CAstPrinter
   * and produces a full HAST FlatBuffer (ast_buffer) instead of the stub.
   * Must be called before the first decompile call.
   */
  setUseCastLayer(useCast: boolean): void
  /**
   * Add a variable rename mapping (old_name → new_name).
   * When the C AST layer is active, all variable references matching
   * old_name will be replaced with new_name in the decompiled output.
   * Call before decompileIr(). Multiple renames accumulate.
   */
  addVariableRename(oldName: string, newName: string): void
  /**
   * Clear all variable renames. Call between decompile invocations
   * if the rename set changes.
   */
  clearVariableRenames(): void
  /**
   * Provide the authoritative function-start table (entry addresses from
   * the Pathfinder `analyzeAll` function list) to the engine BEFORE
   * decompileIr().  Stamped as the `helix.function_starts` module attribute
   * in `Pipeline::translateToMLIR`, this is what makes
   * `functionTableIsAuthoritative_` true for an isolated/IDE single-function
   * lift, so the D2 callee-gate and the #30 registry-miss honesty path fire
   * instead of degrading to the regression-safe non-gating fallback.
   * Additive: callers that never call it keep today's behaviour (table
   * derived from FuncOp entries only, non-authoritative for a lone lift).
   * Replaces the full set on each call; pass the complete table.
   */
  setFunctionStarts(starts: Array<number>): void
  /**
   * Provide versioned function signatures and nominal struct layouts from
   * DWARF/BTF/PDB. Pass an empty string to clear metadata between files.
   */
  setDebugTypeInfoJson(json: string): void
  /**
   * Register a virtual-address range with the engine's data-section
   * store.  REQUIRED for switch-table recovery — without at least one
   * section, `RecoverSwitchTables` skips itself and every `switch (...)`
   * in the source binary collapses to `goto default` in the decompiled
   * output.  Call before decompileIr().  Multiple calls accumulate; each
   * call copies the buffer (caller can free immediately).
   *
   * Typical usage from the extension: read the PE/ELF binary's data
   * sections (`.rdata` for MSVC PE, `.rodata` for ELF) and pass the
   * section's virtual address + bytes here once per file.
   */
  addDataSection(vaStart: bigint, bytes: Buffer): void
  /** Drop every registered data section.  Call between binaries. */
  clearDataSections(): void
  /** Get the engine version string. */
  version(): string
  /** Get the target architecture name. */
  architecture(): string
  /**
   * Decompile a binary buffer starting at the given entry address.
   *
   * - `data`: Raw binary data (Buffer)
   * - `base_address`: Base virtual address where the data is loaded (BigInt)
   * - `entry_address`: Entry point address to start decompilation (BigInt)
   */
  decompile(data: Buffer, baseAddress: bigint, entryAddress: bigint): DecompileResult
  /**
   * Decompile Remill LLVM IR text using the **C++ MLIR pipeline**.
   *
   * This is the **primary integration path** for the HexCore IDE.
   * Routes through: LLVM IR → MLIR translation → HelixLow → HelixHigh → Pseudo-C
   *
   * Decompile Remill LLVM IR using the C++ MLIR pipeline.
   *
   * Since v0.7, the Rust HIR pipeline is no longer used as a fallback.
   * If the MLIR engine fails, the error is returned directly.
   */
  decompileIr(irText: string): DecompileResult
  /** Release engine resources. The engine cannot be used after this call. */
  dispose(): void
  /** Check if the engine has been disposed. */
  get isDisposed(): boolean
}

/** Target architecture for the decompiler. */
export declare const enum Architecture {
  X86 = 0,
  X86_64 = 1,
  Arm = 2,
  Aarch64 = 3,
  Mips = 4,
  Mips64 = 5,
  PowerPc = 6,
  PowerPc64 = 7,
  Sparc = 8,
  Sparc64 = 9,
  Riscv32 = 10,
  Riscv64 = 11
}

/** Result of a decompilation operation. */
export interface DecompileResult {
  /** Decompiled pseudo-C source code. */
  source: string
  /** Function name. */
  functionName: string
  /** Entry address as hex string. */
  entryAddress: string
  /** Number of basic blocks in the CFG. */
  blockCount: number
  /** Number of instructions analyzed. */
  instructionCount: number
  /** Raw FlatBuffer data for the CFG (for Graph View zero-copy rendering). */
  cfgBuffer?: Buffer
  /** Raw FlatBuffer data for the AST (for AST View zero-copy rendering). */
  astBuffer?: Buffer
  /** Which pipeline was used: "mlir" or "rust" */
  pipeline: string
}

/**
 * Read the function name from a CFG FlatBuffer without full deserialization.
 *
 * Demonstrates zero-copy access — reads directly from the buffer.
 */
export declare function readCfgFunctionName(buffer: Buffer): string | null

/**
 * Serialize a decompiled AST into a FlatBuffer for the AST View.
 *
 * Takes a JSON string with AST data and returns a FlatBuffer binary.
 */
export declare function serializeAst(astJson: string): Buffer

/**
 * Serialize a control flow graph into a FlatBuffer for the Graph View.
 *
 * Takes a JSON string with CFG data and returns a FlatBuffer binary.
 */
export declare function serializeCfg(cfgJson: string): Buffer
