/* eslint-disable */
/* tslint:disable */
/* auto-generated by NAPI-RS */

/**
 * @hexcore/elixir — Native binary loader
 *
 * Project Azoth — clean-room dynamic analysis framework.
 * Automatically loads the correct platform-specific native binary.
 * Supported platforms: win32-x64, linux-x64, darwin-arm64, darwin-x64.
 */

const { existsSync, readFileSync } = require('fs');
const { join } = require('path');

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
    if (!process.report || typeof process.report.getReport !== 'function') {
        try {
            const lddPath = require('child_process')
                .execSync('which ldd')
                .toString()
                .trim();
            return readFileSync(lddPath, 'utf8').includes('musl');
        } catch {
            return true;
        }
    } else {
        const report = process.report.getReport();
        const rpt = typeof report === 'string' ? JSON.parse(report) : report;
        return !rpt.header.glibcVersionRuntime;
    }
}

switch (platform) {
    case 'win32':
        switch (arch) {
            case 'x64':
                localFileExisted = existsSync(
                    join(__dirname, 'hexcore-elixir.win32-x64-msvc.node')
                );
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./hexcore-elixir.win32-x64-msvc.node');
                    } else {
                        nativeBinding = require('@hexcore/elixir-win32-x64-msvc');
                    }
                } catch (e) {
                    loadError = e;
                }
                break;
            default:
                throw new Error(`Unsupported architecture on Windows: ${arch}`);
        }
        break;

    case 'linux':
        switch (arch) {
            case 'x64':
                if (isMusl()) {
                    localFileExisted = existsSync(
                        join(__dirname, 'hexcore-elixir.linux-x64-musl.node')
                    );
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./hexcore-elixir.linux-x64-musl.node');
                        } else {
                            nativeBinding = require('@hexcore/elixir-linux-x64-musl');
                        }
                    } catch (e) {
                        loadError = e;
                    }
                } else {
                    localFileExisted = existsSync(
                        join(__dirname, 'hexcore-elixir.linux-x64-gnu.node')
                    );
                    try {
                        if (localFileExisted) {
                            nativeBinding = require('./hexcore-elixir.linux-x64-gnu.node');
                        } else {
                            nativeBinding = require('@hexcore/elixir-linux-x64-gnu');
                        }
                    } catch (e) {
                        loadError = e;
                    }
                }
                break;
            default:
                throw new Error(`Unsupported architecture on Linux: ${arch}`);
        }
        break;

    case 'darwin':
        switch (arch) {
            case 'x64':
                localFileExisted = existsSync(
                    join(__dirname, 'hexcore-elixir.darwin-x64.node')
                );
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./hexcore-elixir.darwin-x64.node');
                    } else {
                        nativeBinding = require('@hexcore/elixir-darwin-x64');
                    }
                } catch (e) {
                    loadError = e;
                }
                break;
            case 'arm64':
                localFileExisted = existsSync(
                    join(__dirname, 'hexcore-elixir.darwin-arm64.node')
                );
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./hexcore-elixir.darwin-arm64.node');
                    } else {
                        nativeBinding = require('@hexcore/elixir-darwin-arm64');
                    }
                } catch (e) {
                    loadError = e;
                }
                break;
            default:
                throw new Error(`Unsupported architecture on macOS: ${arch}`);
        }
        break;

    default:
        throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
    if (loadError) {
        // Degrade gracefully — the standalone GitHub Release may not have
        // published the prebuilt .node yet. Consumers should feature-detect.
        console.warn(
            `[hexcore-elixir] Native binding not available on ${platform}-${arch}. ` +
            `The Elixir emulator will be unavailable until the prebuilt .node is installed.`
        );
        module.exports = {
            getVersion: () => '0.0.0-unavailable',
            isAvailable: false,
            loadError: loadError.message
        };
        return;
    }
    throw new Error(
        `Failed to load native binding for @hexcore/elixir on ${platform}-${arch}`
    );
}

// Re-export the full native surface (getVersion, Emulator, Interceptor,
// Stalker, snapshotSave, snapshotRestore, ...) so downstream extensions
// see everything the NAPI-RS bridge exposes, not just getVersion.
for (const key of Object.keys(nativeBinding)) {
    module.exports[key] = nativeBinding[key];
}
module.exports.isAvailable = true;
