/* eslint-disable */
/* tslint:disable */
/* auto-generated by NAPI-RS */

/**
 * @hexcore/elixir — TypeScript Type Declarations
 *
 * Project Azoth — clean-room dynamic analysis, emulation, and
 * instrumentation framework. Replaces Qiling and brings Frida-style
 * Interceptor/Stalker to HexCore's emulation layer.
 *
 * Delivered as a thin NAPI-RS wrapper. The full engine source
 * (C++23 + Rust) lives in the standalone repo:
 *   https://github.com/AkashaCorporation/hexcore-elixir
 */

/** Get the engine version string. */
export function getVersion(): string;

/** Whether the native binding loaded successfully on this platform. */
export const isAvailable: boolean;

/** On load failure, contains the underlying error message. */
export const loadError: string | undefined;

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

export interface EmulatorConfig {
	/** Target architecture. Currently only `x86_64` is supported. */
	arch: 'x86_64';
	/** Hard cap on instructions executed before the emulator forces a stop. */
	maxInstructions: number;
	/** Emit verbose diagnostics to stderr. */
	verbose?: boolean;
}

export type StopReasonKind = 'Exit' | 'InsnLimit' | 'Error' | 'User';

export interface StopReason {
	kind: StopReasonKind;
	address: bigint;
	instructionsExecuted: number;
	message: string;
}

export interface ApiCall {
	address: bigint;
	name: string;
	module: string;
	returnValue: bigint;
	arguments: bigint[];
}

export interface StalkerEvent {
	from: bigint;
	to: bigint;
	count: number;
}

// ---------------------------------------------------------------------------
// Emulator
// ---------------------------------------------------------------------------

export class Emulator {
	constructor(config: EmulatorConfig);

	/** Load a PE or ELF image into the emulator. Returns entry point. */
	load(data: Buffer): bigint;

	/** Run emulation from `start` until `end` (or a stop condition). */
	run(start: bigint, end: bigint): StopReason;

	/** Abort a running emulation. Safe to call from a hook callback. */
	stop(): void;

	memMap(address: bigint, size: number, perms: number): void;
	memRead(address: bigint, size: number): Buffer;
	memWrite(address: bigint, data: Buffer): void;

	// Reg ID is a numeric Unicorn UC_X86_REG_* value (e.g. RIP=41, RAX=35, RSP=44).
	// Elixir does NOT accept register name strings — pass the integer.
	regRead(regId: number): bigint;
	regWrite(regId: number, value: bigint): void;

	getApiCalls(): ApiCall[];
	getApiCallCount(): number;

	// Interceptor bound to this emulator instance
	interceptorAttach(address: bigint, onEnter: ((state: unknown) => void) | null, onLeave: ((state: unknown) => void) | null): void;
	interceptorDetach(address: bigint): void;
	interceptorLogCount(): number;

	// Project Pythia Oracle Hook — native breakpoints (v3.9.0-preview.oracle).
	// run() returns cleanly when PC matches any registered address; stopReason.kind
	// becomes "breakpoint". Call run(currentPc, 0n) to resume.
	breakpointAdd(address: bigint): void;
	breakpointDel(address: bigint): void;
	breakpointClear(): void;

	// Single-step N instructions with an explicit cap. Used by the Oracle
	// bridge to step exactly 1 instruction past a just-removed breakpoint
	// before re-installing it.
	runN(start: bigint, end: bigint, maxInsns: bigint): {
		kind: string;
		address: bigint;
		instructionsExecuted: number;
		message: string;
	};

	// Stalker bound to this emulator instance
	stalkerFollow(): void;
	stalkerUnfollow(): void;
	stalkerBlockCount(): number;
	stalkerExportDrcov(): Buffer;

	// Snapshot save/restore bound to this emulator instance
	snapshotSave(): Buffer;
	snapshotRestore(blob: Buffer): void;

	dispose(): void;
	readonly isDisposed: boolean;
	readonly maxInstructions: number;
}

// ---------------------------------------------------------------------------
// Standalone Interceptor / Stalker classes (alternative to the bound methods)
// ---------------------------------------------------------------------------

export class Interceptor {
	constructor(emulator: Emulator);
	attach(address: bigint, onEnter: ((state: unknown) => void) | null, onLeave: ((state: unknown) => void) | null): void;
	detach(address: bigint): void;
	dispose(): void;
	readonly isDisposed: boolean;
}

export class Stalker {
	constructor(emulator: Emulator);
	follow(): void;
	unfollow(): void;
	drain(): StalkerEvent[];
	blockCount(): number;
	exportDrcov(): Buffer;
	dispose(): void;
	readonly isDisposed: boolean;
}

// ---------------------------------------------------------------------------
// Module-level snapshot helpers (operate on raw blobs)
// ---------------------------------------------------------------------------

export function snapshotSave(emulator: Emulator): Buffer;
export function snapshotRestore(emulator: Emulator, blob: Buffer): void;
