#!/usr/bin/env python3
"""
Copy hexcore-rellic source files to the standalone repo directory.

Copies everything needed for the standalone npm package, excluding:
  - deps/          (too large, distributed as release asset)
  - build/         (compiled output)
  - build-rellic/  (CMake build dir)
  - clang-build/   (Clang build dir)
  - clang-install/ (Clang install dir)
  - z3-download/   (Z3 download cache)
  - node_modules/  (npm install)
  - prebuilds/     (generated by prebuildify)
  - _rebuild_all.py     (internal build orchestrator)
  - _rebuild_mt.py      (internal build script, if present)
  - _build_clang.py     (internal build script)
  - _build_rellic.py    (internal build script)
  - _build_z3.py        (internal build script)
  - _pack_deps.py       (internal build script)
  - _copy_to_standalone.py (this script)

Usage:
  python _copy_to_standalone.py
  python _copy_to_standalone.py --target C:\\path\\to\\standalone

Copyright (c) HikariSystem. All rights reserved.
Licensed under MIT License.
"""
import os
import sys
import shutil
import argparse

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_TARGET = r"C:\Users\Mazum\Desktop\StandalonePackagesHexCore\hexcore-rellic"

EXCLUDE_DIRS = {
    "deps", "build", "build-rellic", "clang-build", "clang-install",
    "z3-download", "node_modules", "prebuilds", ".git", "__pycache__",
}

EXCLUDE_FILES = {
    "_rebuild_all.py",
    "_rebuild_mt.py",
    "_build_clang.py",
    "_build_rellic.py",
    "_build_z3.py",
    "_pack_deps.py",
    "_copy_to_standalone.py",
}


def copy_to_standalone(target):
    if not os.path.isdir(target):
        os.makedirs(target, exist_ok=True)
        print(f"Created {target}")

    copied = 0
    for root, dirs, files in os.walk(SCRIPT_DIR):
        # Skip excluded directories
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]

        for f in files:
            if f in EXCLUDE_FILES:
                continue

            src = os.path.join(root, f)
            rel = os.path.relpath(src, SCRIPT_DIR)
            dst = os.path.join(target, rel)

            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(src, dst)
            print(f"  {rel}")
            copied += 1

    # Create deps/README.md explaining how to get deps
    deps_readme = os.path.join(target, "deps", "README.md")
    os.makedirs(os.path.dirname(deps_readme), exist_ok=True)
    with open(deps_readme, "w", encoding="utf-8") as f:
        f.write("""# Dependencies

This directory should contain the pre-compiled native dependencies.

## Directory Structure

```
deps/
├── llvm/
│   ├── include/          # LLVM 18.1.8 headers
│   └── lib/              # LLVM 18 static libs (~78 libs)
├── clang/
│   ├── include/          # Clang 18.1.8 headers
│   └── lib/              # Clang 18 static libs (10 libs)
├── z3/
│   ├── include/          # Z3 headers (z3.h, z3++.h)
│   └── lib/              # Z3 static lib (libz3.lib)
└── rellic/
    ├── include/rellic/   # Rellic pass headers
    └── lib/              # Rellic static lib (rellic.lib)
```

## For CI (GitHub Actions)

Dependencies are automatically downloaded from the GitHub Release
asset `rellic-deps-win32-x64.zip` during the prebuild workflow.

## For local development

Download the deps zip from the latest release:
```powershell
gh release download v0.1.0 -p "rellic-deps-win32-x64.zip" -R LXrdKnowkill/hexcore-rellic
Expand-Archive rellic-deps-win32-x64.zip -DestinationPath .
```

Or build from source using the monorepo build scripts:
```powershell
cd <monorepo>/extensions/hexcore-rellic
python _rebuild_all.py
```
""")
    copied += 1
    print(f"  deps/README.md (generated)")

    print(f"\n{copied} files copied to {target}")
    print(f"\nNext steps:")
    print(f"  1. cd {target}")
    print(f"  2. npm install")
    print(f"  3. git add -A && git commit -m 'feat: initial rellic N-API wrapper with LLVM 18 stub pipeline'")
    print(f"  4. git push origin main")
    print(f"  5. Pack deps: cd <monorepo>/extensions/hexcore-rellic && python _pack_deps.py")
    print(f"  6. Upload deps zip: gh release create v0.1.0 rellic-deps-win32-x64.zip -R LXrdKnowkill/hexcore-rellic")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Copy to standalone repo")
    parser.add_argument("--target", "-t", default=DEFAULT_TARGET,
                        help=f"Target directory (default: {DEFAULT_TARGET})")
    args = parser.parse_args()
    copy_to_standalone(args.target)
